#端口号
server:
  port: 8080
#项目名称
  servlet:
    application-display-name: IESystem

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/lesystem?serverTimezone=UTC
      username: root
      password: 123456

#mapper文件配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  #mapper包名简称
  type-aliases-package: com.example.iesystem.pojo
